################
### MONITORS ###
################

## See https://wiki.hypr.land/Configuring/Monitors/
#monitor=,preferred,auto,auto, mirror, DP-2
#monitor=DP-2,3840x2160@60,0x0,1.5
##monitor=DP-4,3440x1440@144,0x0,1


monitor=,preferred,auto,auto,mirror,DP-4
monitor=DP-4,3440x1440@144,0x0,1
monitor=DP-2,disable


